# Generated by Django 3.0.7 on 2020-07-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('karma_points_earned', models.IntegerField(null=True)),
                ('karma_points_used', models.IntegerField(null=True)),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Consumer')),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Merchant')),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.Offers')),
            ],
        ),
    ]
