# Generated by Django 3.0.7 on 2020-06-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('accounts', '0002_auto_20200630_1219'),
        ('karmapoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.Offers'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Consumer'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Merchant'),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
