# Generated by Django 3.0.7 on 2020-06-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karmapoints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='curr_lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='consumer',
            name='curr_long',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
