# Generated by Django 3.0.7 on 2020-06-30 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_card_details'),
        ('karmapoints', '0002_auto_20200629_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Consumer'),
        ),
        migrations.DeleteModel(
            name='Consumer',
        ),
    ]
