# Generated by Django 3.0.7 on 2020-06-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20200630_1735'),
        ('karmapoints', '0002_auto_20200630_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.Merchant'),
        ),
    ]
