# Helper function to get transaction status from action code returned by response
def action_code_to_txn_status(argument):
	switcher = { 
		'00': "Approved and completed successfully", 
		'01': "Refer to card issuer", 
		'02': "Refer to card issuer, special condition",
		'03': "Invalid merchant",
		'04': "Pick up card (no fraud)", 
		'05': "Do not honor",
		'06': "Error",
		'07': "Pick up card, special condition (fraud account)",
		'10': "Partial approval",
		'11': "Approved (V.I.P)",
		'12': "Invalid transaction",
		'13': "Invalid amount or currency conversion field overflow",
		'14': "Invalid account number (no such number)",
		'15': "No such issuer",
		'19': "Re-enter transaction",
		'21': "No action taken",
		'25': "Unable to locate record in file",
		'28': "File temporarily not available for update or inquiry",
		'39': "No credit account",
		'41': "Lost card, pick up (fraud account)",
		'43': "Stolen card, pick up (fraud account)",
		'51': "Not sufficient funds",
		'52': "No checking account",
		'53': "No savings account",
		'54': "Expired card or expiration date is missing",
		'55': "Incorrect PIN or PIN missing",
		'57': "Transaction not permitted to cardholder",
		'59': "Suspected fraud",
		'61': "Exceeds approval amount limit",
		'62': "Restricted card (card invalid in this region or country)",
		'63': "Security violation (source is not correct issuer)",
		'64': "Transaction does not fulfill AML requirement",
		'65': "Exceeds withdrawal frequency limit",
		'75': "Allowable number of PIN entry tries exceeded",
		'76': "Unsolicited reversal",
		'79': "Already reversed (by Switch)",
		'80': "No financial impact",
		'81': "Cryptographic error found in PIN",
		'82': "Negative CAM, dCVV, iCVV, or CVV results",
		'85': "No reason to decline a request for address verification, CVV2 verification, or a credit voucher or merchandise return",
		'86': "Cannot verify PIN; for example, no PVV",
		'89': "Ineligible to receive financial position information (GIV)",
		'91': "Issuer or switch inoperative and STIP not applicable or not available for this transaction",
		'92': "Financial institution or intermediate network facility cannot be found for routing (receiving institution ID is invalid)",
		'93': "Transaction cannot be completed - violation of law",
		'94': "Duplicate transmission",
		'96': "System malfunction or certain field error conditions",
		'B2': "Surcharge amount not supported by debit network issuer.",
		'N0': "Force STIP",
		'N3': "Cash service not available",
		'N4': "Cash request exceeds issuer or approved limit",
		'N5': "Ineligible for resubmission",
		'N7': "Decline for CVV2 failure",
		'N8': "Transaction amount exceeds preauthorized approval amount",
		'Q1': "Card Authentication failed",
		'R0': "Stop Payment Order"
	} 
	return switcher.get(argument, "Invalid action code")