# Generated by Django 3.0.7 on 2020-07-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=200, null=True)),
                ('karma_points_required', models.IntegerField(null=True)),
                ('percentage_off', models.IntegerField(null=True)),
                ('offer_start_date', models.DateField(auto_now_add=True, null=True)),
                ('offer_end_date', models.DateField(null=True)),
                ('days_valid', models.IntegerField(null=True)),
                ('details', models.TextField(null=True)),
                ('merchant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Merchant')),
            ],
        ),
    ]
