# Generated by Django 3.0.7 on 2020-06-30 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karmapoints', '0002_auto_20200630_1219'),
        ('accounts', '0002_auto_20200630_1219'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Merchant'),
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
