# Generated by Django 3.0.7 on 2020-06-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_auto_20200630_1735'),
        ('offers', '0002_auto_20200630_1219'),
    ]

    operations = [
    ]
