# Generated by Django 3.0.7 on 2020-06-21 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin-panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='business_category',
        ),
        migrations.AddField(
            model_name='consumer',
            name='current_karma_points',
            field=models.IntegerField(null=True),
        ),
    ]
