# Generated by Django 3.0.7 on 2020-06-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin-panel', '0002_auto_20200621_0208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=200, null=True)),
                ('annual_revenue', models.IntegerField(null=True)),
                ('business_category', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('card_details', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karma_points', models.IntegerField(null=True)),
                ('percentage_off', models.IntegerField(null=True)),
                ('offer_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('days_valid', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.IntegerField(null=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('discount_amount', models.IntegerField(null=True)),
                ('karma_points_earned', models.IntegerField(null=True)),
                ('karma_points_used', models.IntegerField(null=True)),
            ],
        ),
    ]
