# Generated by Django 3.0.7 on 2020-06-22 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin-panel', '0003_merchant_offers_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin-panel.Consumer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin-panel.Merchant'),
        ),
    ]
