# Generated by Django 3.0.7 on 2020-06-22 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin-panel', '0005_auto_20200622_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin-panel.Merchant'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='consumer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin-panel.Consumer'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin-panel.Merchant'),
        ),
    ]
